" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif


" +----------------------------------+
" |              快捷键              |
" +----------------------------------+
nmap H 10h
nmap J 10j
nmap K 10k
nmap L 10l

let mapleader=" "
nmap <Leader>W :w<CR>:q<CR>
nmap <Leader>w :w<CR>
nmap <Leader>q :q<CR>
nmap <leader>Q :q!<CR>

" 定义快捷键在结对符之间跳转
nmap <Leader>m %

" 查找
nmap <Leader>f *
nmap <Leader>F #
" 折叠
nmap <Leader>] zM
nmap <Leader>[ zR
nmap <Leader>a za
" 多窗口光标移动
nnoremap <Leader>e <C-W><C-W>
nnoremap <Leader>h <C-W>h
nnoremap <Leader>j <C-W>j
nnoremap <Leader>k <C-W>k
nnoremap <Leader>l <C-W>l
" 移动屏幕
nnoremap <Leader>H <C-W>H
nnoremap <Leader>J <C-W>J
nnoremap <Leader>K <C-W>K
nnoremap <Leader>L <C-W>L
" 缩放屏幕
nnoremap <Leader>= <C-W>=
nnoremap <Leader>+ <C-W>+
nnoremap <Leader>- <C-W>-
" 移动tab
nnoremap <Leader>t gt
nnoremap <Leader>T gT


" +----------------------------------+
" |               基本               |
" +----------------------------------+
set encoding=utf-8
" 光标遇到括号时, 自动高亮对应的另一个大括号
set noshowmatch
" 不与 Vi 兼容
set nocompatible
" 打开语法高亮。自动识别代码, 使用多种颜色显示 自动开启
syntax on
" 启用256色
set t_Co=256
" 载入与文件对应的缩进规则
filetype indent on

" +----------------------------------+
" |               外观               |
" +----------------------------------+
" 显示行号
set number
" 显示光标所在的当前行的行号, 其他行都为相对于该行的相对行号
set relativenumber
" 光标所在的当前行高亮
set cursorline
" 在底部显示, 当前处于命令模式还是插入模式
set showmode
" 在状态栏底部显示光标的当前位置(位于哪一行哪一列)
set ruler
" 命令模式下, 在底部显示当前键入的指令
set showcmd

" +----------------------------------+
" |               搜索               |
" +----------------------------------+
" 搜索时, 不高亮显示匹配结果
set nohlsearch
" 输入搜索模式时, 每输入一个字符, 就自动跳到第一个匹配的结果
set incsearch
" 搜索时忽略大小写
set ignorecase
" 如果同时打开了ignorecase, 那么对于只有一个大写字母的搜索词, 将大小写敏感; 其他情况都是大小写不敏感
set smartcase

" +----------------------------------+
" |               缩进               |
" +----------------------------------+
" 按下Tab键时, Vim显示的空格数(此时tab还是制表符, 只不过长度为两个空格)
set tabstop=4
" 自动将Tab转为空格
set expandtab
" Tab转为多少个空格, 和上面两句等价
" set softtabstop=4
" 按下回车键后, 下一行的缩进会自动跟上一行的缩进保持一致
set autoindent
" 在文本上按下>>(增加一级缩进)、<<(取消一级缩进)或者==(取消全部缩进)时, 每一级的字符数
set shiftwidth=4
" 只有遇到指定的符号(比如空格、连词号和其他标点符号), 才发生折行. 也就是说, 不会在单词内部折行
set linebreak

" +----------------------------------+
" |               折叠               |
" +----------------------------------+
" za, 打开或关闭当前折叠; zM, 关闭所有折叠; zR, 打开所有折叠
" 基于缩进进行代码折叠
" set foldmethod=indent
" 基于语法进行代码折叠
set foldmethod=syntax
" 启动 vim 时关闭折叠代码
set nofoldenable

" +----------------------------------+
" |             vim-plug             |
" +----------------------------------+
" call plug#begin()
" Plug 'itchyny/lightline.vim'
" Plug 'preservim/NERDTree'
" call plug#end()
" |------------ lightline ------------|
" set laststatus=2
" set noshowmode